MVC/ViewModels/MaintenanceViewModel.cs
using MaintenanceTracker.Core.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MaintenanceTracker.MVC.ViewModels
{
    public class MaintenanceViewModel
    {
        #region Properties

        public Guid MaintenanceId { get; set; }
        public Guid VehicleId { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Range(.01, 999999, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public int Mileage { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DateOfService { get; set; }

        public decimal Cost { get; set; }
        public decimal Tax { get; set; }
        public decimal TotalCost { get; set; }
        public Vehicle Vehicle { get; set; }
        public ICollection<Part> Parts { get; set; }

        #endregion

        #region Methods

        public static implicit operator MaintenanceViewModel(Maintenance maintenance)
        {
            return new MaintenanceViewModel
            {
                MaintenanceId = maintenance.Id,
                VehicleId = maintenance.Vehicle.Id,
                Description = maintenance.Description,
                Mileage = maintenance.Mileage,
                DateOfService = maintenance.DateOfService,
                Cost = maintenance.Cost,
                TotalCost = maintenance.TotalCost,
                Vehicle = maintenance.Vehicle,
                Parts = maintenance.Parts,
            };
        }

        public static implicit operator Maintenance(MaintenanceViewModel vm)
        {
            return new Maintenance
            {
                Id = vm.MaintenanceId,
                Description = vm.Description,
                Mileage = vm.Mileage,
                DateOfService = vm.DateOfService,
                Cost = vm.Cost,
                TotalCost = vm.TotalCost,
                Vehicle = vm.Vehicle,
                Parts = vm.Parts,
            };
        }

        #endregion
    }
}

MVC/Controllers/MaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using MaintenanceTracker.Core.Models;
using MaintenanceTracker.Core.Services;
using MaintenanceTracker.MVC.ViewModels;

namespace MaintenanceTracker.MVC.Controllers
{
    public class MaintenanceController : BaseController
    {
        #region Fields

        private readonly IMaintenanceService _maintenanceService;
        private readonly IVehicleService _vehicleService;

        #endregion

        #region Constructors

        public MaintenanceController() { }

        public MaintenanceController(IMaintenanceService maintenanceService, IVehicleService vehicleService)
        {
            _maintenanceService = maintenanceService;
            _vehicleService = vehicleService;
        }

        #endregion

        #region Routes

        // GET: Maintenance/Details/5
        public ActionResult Details(Guid id)
        {
            var maintenance = _maintenanceService.FindServiceById(id);

            if (maintenance == null) return HttpNotFound();

            MaintenanceViewModel vm = maintenance;
            return View(vm);
        }

        // GET: Maintenance/Create
        public ActionResult Create(Guid vehicleId)
        {
            if (_vehicleService.FindVehicleById(vehicleId) == null) return HttpNotFound();

            ViewBag.VehicleId = vehicleId;
            Session["parts"] = new List<Part>();

            return View(new MaintenanceViewModel());
        }

        // GET: Maintenance/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Mileage,DateOfService,Description,Cost")] Guid vehicleId, MaintenanceViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            var vehicle = _vehicleService.FindVehicleById(vehicleId);
            Maintenance maintenance = vm;
            maintenance.Id = Guid.NewGuid();
            maintenance.Parts = (List<Part>) Session["parts"];

            _maintenanceService.AddMaintenance(vehicleId, maintenance);
            _vehicleService.UpdateVehicle(vehicle);

            return RedirectToAction("Details", "Maintenance", new { id = maintenance.Id });
        }

        // GET: Maintenance/Edit/5
        public ActionResult Edit(Guid id)
        {
            var maintenance = _maintenanceService.FindServiceById(id);

            if (maintenance == null) return HttpNotFound();

            MaintenanceViewModel vm = maintenance;
            return View(vm);
        }

        // GET: Maintenance/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaintenanceId,Mileage,DateOfService,Description,Parts")] MaintenanceViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Maintenance maintenance = vm;

            _maintenanceService.UpdateMaintenance(maintenance);

            return RedirectToAction("Details", "Maintenance", new { id = maintenance.Id });
        }

        // GET: Maintenance/Delete
        public ActionResult Delete(Guid id)
        {
            var maintenance = _maintenanceService.FindServiceById(id);

            if (maintenance == null) return HttpNotFound();

            MaintenanceViewModel vm = maintenance;
            return View(vm);
        }

        // GET: Maintenance/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var vehicleId = _maintenanceService.FindServiceById(id).Vehicle.Id;

            _maintenanceService.RemoveMaintenance(id);

            return RedirectToAction("Details", "Vehicle", new { id = vehicleId });
        }

        #endregion
    }
}

MVC/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MaintenanceTracker.Core.Models;
using MaintenanceTracker.Core.Services;
using MaintenanceTracker.MVC.Helpers;
using MaintenanceTracker.MVC.ViewModels;

namespace MaintenanceTracker.MVC.Controllers
{
    public class PartController : Controller
    {
        #region Fields

        private readonly IMaintenanceService _maintenanceService;

        #endregion

        #region Constructors

        public PartController() { }

        public PartController(IMaintenanceService maintenanceService)
        {
            _maintenanceService = maintenanceService;
        }

        #endregion

        #region Routes

        // GET: Part/Create
        public ActionResult Create(Guid maintenanceId)
        {
            if (_maintenanceService.FindServiceById(maintenanceId) == null) return HttpNotFound();

            ViewBag.MaintenanceId = maintenanceId;

            return View(new PartViewModel());
        }

        // GET: Part/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductName,ModelNumber,Price,Quantity")] Guid maintenanceId, PartViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Part part = vm;

            _maintenanceService.AddPart(maintenanceId, part);

            return RedirectToAction("Details", "Maintenance", new { id = maintenanceId });
        }

        // GET: Part/Edit/5
        public ActionResult Edit(Guid maintenanceId, Guid id)
        {
            var part = _maintenanceService.FindPartById(id);

            if (part == null) return HttpNotFound();

            PartViewModel vm = part;
            ViewBag.MaintenanceId = maintenanceId;

            return View(vm);
        }

        // GET: Part/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ModelNumber,Price,Quantity")] Guid maintenanceId, PartViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Part part = vm;

            _maintenanceService.UpdatePart(maintenanceId, part);

            return RedirectToAction("Details", "Maintenance", new { id = maintenanceId });
        }

        // GET: Part/Delete
        public ActionResult Delete(Guid maintenanceId, Guid id)
        {
            var part = _maintenanceService.FindPartById(id);
            var maintenance = _maintenanceService.FindServiceById(maintenanceId);

            if (part == null || maintenance == null) return HttpNotFound();

            PartViewModel vm = part;
            ViewBag.MaintenanceId = maintenance.Id;

            return View(vm);
        }

        // GET: Part/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid maintenanceId, Guid id)
        {
            _maintenanceService.RemovePart(maintenanceId, id);

            return RedirectToAction("Details", "Maintenance", new { id = maintenanceId });
        }

        #endregion

        public JsonResult AddPart(PartViewModel model)
        {
            var parts = (List<Part>)Session["parts"];
            model.PartId = Guid.NewGuid();
            model.TotalCost = model.Price * model.Quantity;

            parts.Add(model);

            Session["parts"] = parts;

            return Json(new
            {
                success = true,
                html = this.RenderPartialToString("_TableRow", model),
                totalCost = parts.Sum(p => ((PartViewModel)p).TotalCost),
                part = model
            });
        }

        public JsonResult RemovePart(Guid id)
        {
            var parts = (List<Part>)Session["parts"];
            parts.RemoveAll(p => p.Id.Equals(id));

            Session["parts"] = parts;

            return Json(new
            {
                hasParts = parts.Any(),
                totalCost = parts.Any() ? parts.Sum(p => ((PartViewModel)p).TotalCost) : 0m
            });
        }
    }
}

MVC/Controllers/VehicleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MaintenanceTracker.Core.Models;
using MaintenanceTracker.Core.Services;
using MaintenanceTracker.MVC.ViewModels;

namespace MaintenanceTracker.MVC.Controllers
{
    public class VehicleController : BaseController
    {
        #region Fields

        private readonly IVehicleService _vehicleService;

        #endregion

        #region Constructors

        public VehicleController() { }

        public VehicleController(IVehicleService vehicleService)
        {
            _vehicleService = vehicleService;
        }

        #endregion

        #region Routes

        // GET: Vehicle
        public ActionResult Index()
        {
            var vehicles = _vehicleService.FindAllVehicles().OrderByDescending(v => v.Year);
            return vehicles.Any() 
                ? View(vehicles.Select(v => (VehicleViewModel)v)) 
                : View("_NoneFound");
        }

        // GET: Vehicle/Details/5
        public ActionResult Details(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            return View(vm);
        }

        // GET: Vehicle/Create
        public ActionResult Create()
        {
            return View(new VehicleViewModel
            {
                Makes = _vehicleService.FindAllMakes(),
                Models = _vehicleService.FindAllModels()
            });
        }

        // POST: Vehicle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VIN,LicensePlate,Year,Make,Model,DatePurchased,PriceAtPurchase,MileageAtPurchase,CurrentMileage,Services")] VehicleViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Vehicle vehicle = vm;
            vehicle.Id = Guid.NewGuid();

            _vehicleService.CreateVehicle(vehicle);

            return RedirectToAction("Index");
        }

        // GET: Vehicle/Edit/5
        public ActionResult Edit(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            vm.Makes = _vehicleService.FindAllMakes();
            vm.Models = _vehicleService.FindAllModels().Where(m => m.Make.Description.Equals(vm.Make));

            return View(vm);
        }

        // GET: Vehicle/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleId,VIN,LicensePlate,Year,Make,Model,DatePurchased,PriceAtPurchase,MileageAtPurchase,CurrentMileage")] VehicleViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Vehicle vehicle = vm;
            _vehicleService.UpdateVehicle(vehicle);

            return RedirectToAction("Index");
        }

        // GET: Vehicle/Delete/5
        public ActionResult Delete(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            return View(vm);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            _vehicleService.DeleteVehicle(vehicle);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetModelsForMake(string make)
        {
            var modelsForMake = _vehicleService.FindAllModels()
                                    .Where(m => m.Make.Description.Equals(make) && !m.Description.ToLowerInvariant().Contains("other"))
                                    .Select(m => m.Description);

            return Json(new { models = modelsForMake });
        }

        #endregion
    }
}

MVC/Views/Maintenance/Create.cshtml
@using MaintenanceTracker.MVC.ViewModels
@model MaintenanceViewModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm(new { vehicleId = ViewBag.VehicleId }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row xl-mt">
        <h2>@ViewBag.Title Maintenance</h2>
        <div class="container form-horizontal">
            @Html.Partial("~/Views/Part/_PartFields.cshtml", new PartViewModel())
            <div class="row lg-mt">
                <div class="col-sm-6">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-3">
                                @Html.Label("Date", new {@class = "control-label"})
                                <div class="input-group date" id="datepicker">
                                    <input name="DateOfService" class="form-control" placeholder="MM/DD/YYYY" type="text"/>
                                    @Html.ValidationMessageFor(model => model.DateOfService, "", new {@class = "text-danger"})
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                @Html.Label("Mileage", new {@class = "control-label"})
                                @Html.TextBoxFor(model => model.Mileage, new {@class = "form-control"})
                                @Html.ValidationMessageFor(model => model.Mileage, "", new {@class = "text-danger"})
                            </div>
                            <div class="col-sm-3">
                                @Html.Label("Cost", new {@class = "control-label"})
                                <div class="input-group">
                                    <div class="input-group-addon">$</div>
                                    @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(model => model.Cost, "", new {@class = "text-danger"})
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-9">
                                @Html.Label("Description", new {@class = "control-label"})
                                @Html.TextAreaFor(model => model.Description, new {@class = "form-control", @rows = 2})
                                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row md-mt">
            <div class="form-group">
                <div class="col-sm-10">
                    <input type="submit" value="Create" class="btn btn-success"/>
                    @Html.ActionLink("Cancel", "Details", "Vehicle", new {id = ViewBag.VehicleId}, new {@class = "btn btn-default"})
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/forms")
    @Scripts.Render("~/Scripts/maintenance-form.js")
}

MVC/Views/Maintenance/Delete.cshtml
@model MaintenanceTracker.MVC.ViewModels.MaintenanceViewModel

@{
    ViewBag.Title = "Delete";
}

<div class="xl-mt">
    <h3>Are you sure you want to delete this?</h3>    
    <hr/>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.DateOfService)</dt>
        <dd>@Html.DisplayFor(model => model.DateOfService)</dd>

        <dt>@Html.DisplayNameFor(model => model.Mileage)</dt>
        <dd>@Html.DisplayFor(model => model.Mileage)</dd>

        <dt>@Html.DisplayNameFor(model => model.Cost)</dt>
        <dd>@Html.DisplayFor(model => model.Cost)</dd>

        <dt>@Html.DisplayNameFor(model => model.Description)</dt>
        <dd>@Html.DisplayFor(model => model.Description)</dd>
    </dl>
    <div class="row">
        <div class="col-sm-5">
            <ul class="list-group sm-mt">
                @if (Model.Parts != null && Model.Parts.Any())
            {
                foreach (var part in Model.Parts)
                {
                    var partCost = $"{part.Price * part.Quantity:C}";

                        <li class="list-group-item">
                            <span class="badge">@Html.DisplayFor(p => partCost)</span>
                            @Html.DisplayFor(p => part.Description)
                        </li>
                    }
                }
            </ul>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning"/>
            @Html.ActionLink("Back to Details", "Details", "Vehicle", new { id = Model.VehicleId }, new { @class = "btn btn-default" })
        </div>
    }
</div>

MVC/Views/Maintenance/Details.cshtml
@model MaintenanceTracker.MVC.ViewModels.MaintenanceViewModel

@{
    ViewBag.Title = "Details";
    var hasParts = Model.Parts != null && Model.Parts.Any();
}

<div class="row xl-mt">
    <h4>
        @ViewBag.Title for Maintenance
        @if (hasParts)
        {
            <span>(including @Model.Parts.Count Parts)</span>
        }
        else
        {
            <span>(without any Parts)</span>
        }
    </h4>
    <hr />
    <div class="row">
        <div class="col-sm-3">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.DateOfService)</dt>
                <dd>@Html.DisplayFor(model => model.DateOfService)</dd>

                <dt>@Html.DisplayNameFor(model => model.Mileage)</dt>
                <dd>@Html.DisplayFor(model => model.Mileage)</dd>

                <dt>@Html.DisplayNameFor(model => model.Cost)</dt>
                <dd>@Html.DisplayFor(model => model.Cost)</dd>

                <dt>@Html.DisplayNameFor(model => model.TotalCost)</dt>
                <dd>@Html.DisplayFor(model => model.TotalCost)</dd>

                <dt>@Html.DisplayNameFor(model => model.Description)</dt>
                <dd>@Html.DisplayFor(model => model.Description)</dd>
            </dl>
        </div>
        <div class="col-sm-7 col-sm-offset-2">
            <div class="row sm-mb">
                @Html.ActionLink("Add Part", "Create", "Part", new { maintenanceId = Model.MaintenanceId }, new { @class = "btn btn-primary" })
            </div>
            <div class="row">
                <table class="table">
                    <tr>
                        <th>@Html.DisplayName("Description")</th>
                        <th>@Html.DisplayName("Model #")</th>
                        <th>@Html.DisplayName("Price")</th>
                        <th>@Html.DisplayName("Quantity")</th>
                        <th></th>
                    </tr>

                    @if (hasParts)
                    {
                        foreach (var item in Model.Parts)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                <td>@Html.DisplayFor(modelItem => item.ModelNumber)</td>
                                <td>@Html.DisplayFor(modelItem => item.Price)</td>
                                <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                                <td>
                                    <a href="@Url.Action("Edit", "Part", new {maintenanceId = Model.MaintenanceId, id = item.Id})"><i class="fa fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Part", new {maintenanceId = Model.MaintenanceId, id = item.Id})"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaintenanceId }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to Vehicle", "Details", "Vehicle", new { id = Model.VehicleId }, new { @class = "btn btn-default" })
</p>

MVC/Views/Maintenance/Edit.cshtml
@model MaintenanceTracker.MVC.ViewModels.MaintenanceViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row xl-mt">
        <h4>@ViewBag.Title Maintenance</h4>
        <hr />
        <div class="container form-horizontal">
            @Html.HiddenFor(model => model.MaintenanceId)
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Date Purchased", new {@class = "control-label"})
                        <div class="input-group date" id="datepicker">
                            @Html.TextBoxFor(model => model.DateOfService, new {@class = "form-control", @Value = Model.DateOfService.ToString("MM/dd/yyyy"), @placeholder = "MM/DD/YYYY"})
                            @Html.ValidationMessageFor(model => model.DateOfService, "", new {@class = "text-danger"})
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.Mileage, new {@class = "control-label"})
                        @Html.EditorFor(model => model.Mileage, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Mileage, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-3">
                        @Html.Label("Cost", new {@class = "control-label"})
                        <div class="input-group">
                            <div class="input-group-addon">$</div>
                            @Html.TextBoxFor(model => model.Cost, new {@class = "form-control", @readonly = "readonly"})
                            @Html.ValidationMessageFor(model => model.Cost, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-9">
                        @Html.Label("Description", new {@class = "control-label"})
                        @Html.TextAreaFor(model => model.Description, new {@class = "form-control", @rows = 2})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
        </div>
        <div class="row md-mt">
            <div class="form-group">
                <div class="col-sm-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Html.ActionLink("Cancel", "Details", "Vehicle", new { id = Model.VehicleId }, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/forms")

    <script type="text/javascript">
        $(function() {
            $('#datepicker').datepicker();
        });
    </script>
}

MVC/Views/Maintenance/_NoneFound.cshtml
@model MaintenanceTracker.MVC.ViewModels.VehicleViewModel

@{
    var lowMileage = Model.CurrentMileage < 30000;
    var recentPurchase =  Model.DatePurchased > DateTime.Now.AddMonths(-6);
}

<tr>
    <td colspan="5">
        <div class="row txt c md-mt">
            @if (lowMileage && recentPurchase)
            {
                <h2>Must be nice not having to do any maintenance yet, huh?</h2>
            }
            else
            {
                <h2>No maintenance yet? Might want to fix that.</h2>
            }
        </div>
    </td>
</tr>