MVC/ViewModels/VehicleViewModel.cs
using MaintenanceTracker.Core.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace MaintenanceTracker.MVC.ViewModels
{
    public class VehicleViewModel
    {
        #region Properties

        public Guid VehicleId { get; set; }

        [StringLength(17, ErrorMessage = "Value for {0} must be {1} characters.", MinimumLength = 17)]
        public string VIN { get; set; }

        [Required]
        [DisplayName("License Plate #")]
        [StringLength(7, ErrorMessage = "Value for {0} must be between {2} and {1} characters.", MinimumLength = 6)]
        public string LicensePlate { get; set; }

        [Required]
        public int Year { get; set; }

        [Required]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        [DisplayName("Date Purchased")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DatePurchased { get; set; }

        [DisplayName("Price At Purchase")]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal PriceAtPurchase { get; set; }

        [DisplayName("Mileage at Purchase")]
        public int MileageAtPurchase { get; set; }

        [Required]
        [DisplayName("Current Mileage")]
        public int CurrentMileage { get; set; }

        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal TotalServiceCosts { get; set; }

        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal MaintenanceToVehicleCost => PriceAtPurchase - TotalServiceCosts;

        public int MilesDriven => CurrentMileage - MileageAtPurchase;
        public int NumberOfServices => Services.Count;

        public ICollection<Maintenance> Services { get; set; }
        public IEnumerable<int> Years => Enumerable.Range(1981, DateTime.Now.Year - 1981 + 1).OrderByDescending(y => y);
        public IEnumerable<Make> Makes { get; set; }
        public IEnumerable<Model> Models { get; set; }

        #endregion

        #region Constructors

        public VehicleViewModel()
        {
            Services = new List<Maintenance>();
        }

        #endregion

        #region Methods

        public static implicit operator VehicleViewModel(Vehicle vehicle)
        {
            return new VehicleViewModel
            {
                VehicleId = vehicle.Id,
                VIN = vehicle.VIN,
                LicensePlate = vehicle.LicensePlate,
                Year = vehicle.Year,
                Make = vehicle.Make,
                Model = vehicle.Model,
                DatePurchased = vehicle.DatePurchased,
                PriceAtPurchase = vehicle.PriceAtPurchase,
                MileageAtPurchase = vehicle.MileageAtPurchase,
                CurrentMileage = vehicle.CurrentMileage,
                Services = vehicle.Services,
                TotalServiceCosts = vehicle.Services.Sum(s => s.TotalCost)
            };
        }

        public static implicit operator Vehicle(VehicleViewModel vm)
        {
            return new Vehicle
            {
                Id = vm.VehicleId,
                VIN = vm.VIN,
                LicensePlate = vm.LicensePlate,
                Year = vm.Year,
                Make = vm.Make,
                Model = vm.Model,
                DatePurchased = vm.DatePurchased,
                PriceAtPurchase = vm.PriceAtPurchase,
                MileageAtPurchase = vm.MileageAtPurchase,
                CurrentMileage = vm.CurrentMileage,
                Services = vm.Services
            };
        }

        #endregion
    }
}

MVC/Controllers/VehicleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MaintenanceTracker.Core.Models;
using MaintenanceTracker.Core.Services;
using MaintenanceTracker.MVC.ViewModels;

namespace MaintenanceTracker.MVC.Controllers
{
    public class VehicleController : BaseController
    {
        #region Fields

        private readonly IVehicleService _vehicleService;

        #endregion

        #region Constructors

        public VehicleController() { }

        public VehicleController(IVehicleService vehicleService)
        {
            _vehicleService = vehicleService;
        }

        #endregion

        #region Routes

        // GET: Vehicle
        public ActionResult Index()
        {
            var vehicles = _vehicleService.FindAllVehicles().OrderByDescending(v => v.Year);
            return vehicles.Any() 
                ? View(vehicles.Select(v => (VehicleViewModel)v)) 
                : View("_NoneFound");
        }

        // GET: Vehicle/Details/5
        public ActionResult Details(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            return View(vm);
        }

        // GET: Vehicle/Create
        public ActionResult Create()
        {
            return View(new VehicleViewModel
            {
                Makes = _vehicleService.FindAllMakes(),
                Models = _vehicleService.FindAllModels()
            });
        }

        // POST: Vehicle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VIN,LicensePlate,Year,Make,Model,DatePurchased,PriceAtPurchase,MileageAtPurchase,CurrentMileage,Services")] VehicleViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Vehicle vehicle = vm;
            vehicle.Id = Guid.NewGuid();

            _vehicleService.CreateVehicle(vehicle);

            return RedirectToAction("Index");
        }

        // GET: Vehicle/Edit/5
        public ActionResult Edit(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            vm.Makes = _vehicleService.FindAllMakes();
            vm.Models = _vehicleService.FindAllModels().Where(m => m.Make.Description.Equals(vm.Make));

            return View(vm);
        }

        // GET: Vehicle/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleId,VIN,LicensePlate,Year,Make,Model,DatePurchased,PriceAtPurchase,MileageAtPurchase,CurrentMileage")] VehicleViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            Vehicle vehicle = vm;
            _vehicleService.UpdateVehicle(vehicle);

            return RedirectToAction("Index");
        }

        // GET: Vehicle/Delete/5
        public ActionResult Delete(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            if (vehicle == null) return HttpNotFound();

            VehicleViewModel vm = vehicle;
            return View(vm);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var vehicle = _vehicleService.FindVehicleById(id);

            _vehicleService.DeleteVehicle(vehicle);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetModelsForMake(string make)
        {
            var modelsForMake = _vehicleService.FindAllModels()
                                    .Where(m => m.Make.Description.Equals(make) && !m.Description.ToLowerInvariant().Contains("other"))
                                    .Select(m => m.Description);

            return Json(new { models = modelsForMake });
        }

        #endregion
    }
}

MVC/Views/Vehicle/Create.cshtml
@model MaintenanceTracker.MVC.ViewModels.VehicleViewModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row xl-mt">
        <h2>@ViewBag.Title Vehicle</h2>
        <hr/>
        <div class="container form-horizontal">
            @* VIN and License Plate # *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("VIN", new {@class = "control-label"})
                        @Html.TextBoxFor(model => model.VIN, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.VIN, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("License Plate", new {@class = "control-label"})
                        @Html.TextBoxFor(model => model.LicensePlate, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.LicensePlate, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
            @* Year, Make, and Model *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Year", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Year,  new SelectList(Model.Years), "Year", new { @class = "form-control", id = "years" })
                        @Html.ValidationMessageFor(model => model.Year, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Make", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Make, new SelectList(Model.Makes, "Description", "Description"), "Make", new { @class = "form-control", id = "makes" })
                        @Html.ValidationMessageFor(model => model.Make, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Model", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Model, Enumerable.Empty<SelectListItem>(), "Model", new { @class = "form-control", id = "models" })
                        @Html.ValidationMessageFor(model => model.Model, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
            @* Purchase Date and Purchase Price *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Date Purchased", new { @class = "control-label" })
                        <div class="input-group date" id="datepicker">
                            <input name="DatePurchased" class="form-control" placeholder="MM/DD/YYYY" type="text"/>
                            @Html.ValidationMessageFor(model => model.DatePurchased, "", new { @class = "text-danger" })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        @Html.Label("Purchase Price", new {@class = "control-label"})
                        @Html.TextBoxFor(model => model.PriceAtPurchase, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.PriceAtPurchase, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
            @* Purchase Mileage and Current Mileage *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Purchase Mileage", new {@class = "control-label"})
                        @Html.TextBoxFor(model => model.MileageAtPurchase, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.MileageAtPurchase, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Current Mileage", new {@class = "control-label"})
                        @Html.TextBoxFor(model => model.CurrentMileage, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.CurrentMileage, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
        </div>
        <div class="row md-mt">
            <div class="form-group">
                <div class="col-sm-10">
                    <input type="submit" value="Create" class="btn btn-success"/>
                    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/forms"),
    @Scripts.Render("~/Scripts/vehicle-form.js")
    
    <script type="text/javascript">
        $(function () {
            $('#makes, #models').prop('disabled', true);

            years.on('change', {
                dependents: [makes, models],
                pickFirst: true
            }, validateChange);

            makes.on('change', {
                dependents: [models],
                callback: function (sv, i) {
                    console.log("Selected value: " + sv);
                    $.post('/Vehicle/GetModelsForMake', { 'make': sv }, function (result) {
                        console.log(result);
                        models.empty();
                        models.append($('<option />').val('').text('Model'));
                        $.each(result.models, function (i, model) {
                            models.append($('<option />').val(model).text(model));
                        });
                    });
                }
            }, validateChange);
        });
    </script>
}

MVC/Views/Vehicle/Delete.cshtml
@model MaintenanceTracker.MVC.ViewModels.VehicleViewModel

@{
    ViewBag.Title = "Delete";
}

<div class="xl-mt">
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.VIN)</dt>
        <dd>@Html.DisplayFor(model => model.VIN)</dd>

        <dt>@Html.DisplayNameFor(model => model.LicensePlate)</dt>
        <dd>@Html.DisplayFor(model => model.LicensePlate)</dd>

        <dt>@Html.DisplayNameFor(model => model.Year)</dt>
        <dd>@Html.DisplayFor(model => model.Year)</dd>

        <dt>@Html.DisplayNameFor(model => model.DatePurchased)</dt>
        <dd>@Html.DisplayFor(model => model.DatePurchased)</dd>

        <dt>@Html.DisplayNameFor(model => model.PriceAtPurchase)</dt>
        <dd>@Html.DisplayFor(model => model.PriceAtPurchase)</dd>

        <dt>@Html.DisplayNameFor(model => model.MileageAtPurchase)</dt>
        <dd>@Html.DisplayFor(model => model.MileageAtPurchase)</dd>

        <dt>@Html.DisplayNameFor(model => model.CurrentMileage)</dt>
        <dd>@Html.DisplayFor(model => model.CurrentMileage)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/Views/Vehicle/Details.cshtml
@using MaintenanceTracker.MVC.ViewModels
@model VehicleViewModel

@{
    ViewBag.Title = "Details";
    var hasServices = Model.Services.Count > 0;
}

<div class="row xl-mt">
    <h3>@ViewBag.Title for @Model.Year @Model.Make @Model.Model</h3>
    <hr />
    <div class="col-sm-3">
        <div class="row">
            <dl class="dl-horizontal">
                <dt>@Html.DisplayNameFor(model => model.VIN)</dt>
                <dd>@Html.DisplayFor(model => model.VIN)</dd>

                <dt>@Html.DisplayNameFor(model => model.LicensePlate)</dt>
                <dd>@Html.DisplayFor(model => model.LicensePlate)</dd>

                <dt>@Html.DisplayNameFor(model => model.Year)</dt>
                <dd>@Html.DisplayFor(model => model.Year)</dd>

                <dt>@Html.DisplayNameFor(model => model.Make)</dt>
                <dd>@Html.DisplayFor(model => model.Make)</dd>

                <dt>@Html.DisplayNameFor(model => model.Model)</dt>
                <dd>@Html.DisplayFor(model => model.Model)</dd>

                <dt>@Html.DisplayNameFor(model => model.CurrentMileage)</dt>
                <dd>@Html.DisplayFor(model => model.CurrentMileage)</dd>

                <dt>@Html.DisplayNameFor(model => model.PriceAtPurchase)</dt>
                <dd>@Html.DisplayFor(model => model.PriceAtPurchase)</dd>

                <dt>@Html.DisplayNameFor(model => model.DatePurchased)</dt>
                <dd>@Html.DisplayFor(model => model.DatePurchased)</dd>

                <dt>@Html.DisplayNameFor(model => model.MileageAtPurchase)</dt>
                <dd>@Html.DisplayFor(model => model.MileageAtPurchase)</dd>
            </dl>
        </div>
        <div class="row md-mt">
            @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleId }, new { @class = "btn btn-primary" })
            @Html.ActionLink("View Vehicles", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
    <div class="col-sm-7 col-sm-offset-2">
        <div class="row sm-mb">
            @Html.ActionLink("Add Service", "Create", "Maintenance", new { vehicleId = Model.VehicleId }, new { @class = "btn btn-primary" })
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayName("Date")</th>
                        <th>@Html.DisplayName("Mileage")</th>
                        <th>@Html.DisplayName("Cost")</th>
                        <th>@Html.DisplayName("Description")</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (hasServices)
                    {
                        foreach (var item in Model.Services)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.DateOfService)</td>
                                <td>@Html.DisplayFor(modelItem => item.Mileage)</td>
                                <td>@Html.DisplayFor(modelItem => item.Cost)</td>
                                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                <td>
                                    <a href="@Url.Action("Edit", "Maintenance", new {id = item.Id})"><i class="fa fa-edit"></i></a>
                                    <a href="@Url.Action("Details", "Maintenance", new {id = item.Id})"><i class="fa fa-list"></i></a>
                                    <a href="@Url.Action("Delete", "Maintenance", new {id = item.Id})"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        @Html.Partial("~/Views/Maintenance/_NoneFound.cshtml", @Model)
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MVC/Views/Vehicle/Edit.cshtml
@model MaintenanceTracker.MVC.ViewModels.VehicleViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row xl-mt">
        <h2>@ViewBag.Title Vehicle</h2>
        <hr />
        <div class="container form-horizontal">
            @Html.HiddenFor(model => model.VehicleId)
            @* VIN and License Plate # *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("VIN", new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.VIN, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("License Plate", new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.LicensePlate, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LicensePlate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @* Year, Make, and Model *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Year", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Year, new SelectList(Model.Years), "Year", new { @class = "form-control", id = "years" })
                        @Html.ValidationMessageFor(model => model.Year, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Make", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Make, new SelectList(Model.Makes, "Description", "Description"), "Make", new { @class = "form-control", id = "makes" })
                        @Html.ValidationMessageFor(model => model.Make, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Model", new {@class = "control-label"})
                        @Html.DropDownListFor(model => model.Model, new SelectList(Model.Models, "Description", "Description"), "Model", new { @class = "form-control", id = "models" })
                        @Html.ValidationMessageFor(model => model.Model, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>
            @* Purchase Date and Purchase Price *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Date Purchased", new { @class = "control-label" })
                        <div class="input-group date" id="datepicker">
                            @Html.TextBoxFor(model => model.DatePurchased, new { @class = "form-control", @Value = Model.DatePurchased.ToString("MM/dd/yyyy"), @placeholder = "MM/DD/YYYY" })
                            @Html.ValidationMessageFor(model => model.DatePurchased, "", new { @class = "text-danger" })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        @Html.Label("Purchase Price", new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.PriceAtPurchase, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PriceAtPurchase, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @* Purchase Mileage and Current Mileage *@
            <div class="row">
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.Label("Mileage At Purchase", new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.MileageAtPurchase, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MileageAtPurchase, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-2">
                        @Html.Label("Current Mileage", new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.CurrentMileage, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CurrentMileage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row md-mt">
            <div class="form-group">
                <div class="col-sm-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/forms"),
    @Scripts.Render("~/Scripts/vehicle-form.js")

    <script type="text/javascript">
        $(function () {
            years.on('change', {
                dependents: [makes, models],
                pickFirst: true
            }, validateChange);

            makes.on('change', {
                dependents: [models],
                callback: function (sv, i) {
                    console.log("Selected value: " + sv);
                    $.post('/Vehicle/GetModelsForMake', { 'make': sv }, function (result) {
                        console.log(result);
                        models.empty();
                        models.append($('<option />').val('').text('Model'));
                        $.each(result.models, function (i, model) {
                            models.append($('<option />').val(model).text(model));
                        });
                    });
                }
            }, validateChange);
        });
    </script>
}

MVC/Views/Vehicle/Index.cshtml
@model IEnumerable<MaintenanceTracker.MVC.ViewModels.VehicleViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="container xl-mt">
    <div class="row md-mt sm-mb">
        <div class="col-sm-2">
            @Html.ActionLink("Create Vehicle", "Create", null, new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="row">
        <table class="table table-bordered txt c">
            <thead>
                <tr>
                    <th></th>
                    <th>@Html.DisplayName("Year")</th>
                    <th>@Html.DisplayName("Make")</th>
                    <th>@Html.DisplayName("Model")</th>
                    <th>@Html.DisplayName("Purchase Price")</th>
                    <th>@Html.DisplayName("Current Mileage")</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="standard-details">
                        <td>
                            <div class="btn btn-default">
                                <i class="fa fa-plus"></i>
                            </div>
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Year)</td>
                        <td>@Html.DisplayFor(modelItem => item.Make)</td>
                        <td>@Html.DisplayFor(modelItem => item.Model)</td>
                        <td>@Html.DisplayFor(modelItem => item.PriceAtPurchase)</td>
                        <td>@Html.DisplayFor(modelItem => item.CurrentMileage)</td>
                        <td>
                            <a href="@Url.Action("Edit", "Vehicle", new { id = item.VehicleId })"><i class="fa fa-edit"></i></a>
                            <a href="@Url.Action("Details", "Vehicle", new { id = item.VehicleId })"><i class="fa fa-list"></i></a>
                            <a href="@Url.Action("Delete", "Vehicle", new { id = item.VehicleId })"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <tr class="extra-details">
                        <td colspan="8">
                            <div class="row">
                                <div class="col-sm-4">
                                    <span><b>VIN</b>: @Html.DisplayFor(modelItem => item.VIN)</span>
                                    <span><b>License Plate</b>: @Html.DisplayFor(modelItem => item.LicensePlate)</span>
                                    <span><b>Purchase Date</b>: @Html.DisplayFor(modelItem => item.DatePurchased)</span>
                                    <span><b>Price at Purchase</b>: @Html.DisplayFor(modelItem => item.PriceAtPurchase)</span>
                                    <span><b>Miles at Purchase</b>: @Html.DisplayFor(modelItem => item.MileageAtPurchase)</span>
                                </div>
                                <div class="col-sm-3 txt c">
                                    Total Cost of Services:
                                    <div class="fs-md">$@item.TotalServiceCosts</div>
                                </div>
                                <div class="col-sm-2 txt c">
                                    <div class="fs-md">@item.NumberOfServices</div>
                                    Services have been performed
                                </div>
                                <div class="col-sm-2 txt c col-sm-offset-1">
                                    Miles driven so far:<br/>
                                    <h1>@item.MilesDriven</h1>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.extra-details').children().hide();

            $('.btn-default').click(function () {
                var btn = $(this).children('.fa');
                var details = $(this).parent().parent().next('.extra-details').children();

                if (details.css('display') === 'none') {
                    details.slideDown('slow', function () {
                        btn.removeClass('fa-plus').addClass('fa-minus');
                    });
                } else {
                    details.slideUp('slow', function () {
                        btn.removeClass('fa-minus').addClass('fa-plus');
                    });
                }
            });
        });
    </script>
}

MVC/Views/Vehicle/_NoneFound.cshtml
<div class="row txt-c xl-mt">
    <h1>Your garage is empty.. Add a new vehicle?</h1>
    @Html.ActionLink("Click here", "Create", null, new { @class = "btn btn-primary sm-mt" })
</div>